# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gpsd2json 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gpsd2json"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mischa Molhoek"]
  s.date = "2018-02-05"
  s.description = "This gem can be used to talk to the gps daemon"
  s.email = "mischamolhoek@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/gpsd2json.rb"
  ]
  s.homepage = "http://github.com/mmolhoek/gpsd2json"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "ruby gem to access the gpsd daemon"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["~> 12.0"])
      s.add_development_dependency(%q<juwelier>, [">= 2.4.0", "~> 2.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<yard-doctest>, ["~> 0.1"])
    else
      s.add_dependency(%q<rake>, ["~> 12.0"])
      s.add_dependency(%q<juwelier>, [">= 2.4.0", "~> 2.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<yard-doctest>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 12.0"])
    s.add_dependency(%q<juwelier>, [">= 2.4.0", "~> 2.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<yard-doctest>, ["~> 0.1"])
  end
end

